name: ListPlayersPlugin
version: 1.0-SNAPSHOT
main: exodian.me.listplayersplugin.ListPlayersPlugin
api-version: 1.13
authors: [SamPom100]
description: Lists all alive players
website: github.com/SamPom100


permissions:
  listplayers.use:
    description: Includes you in the list
    default: true


commands:
  mask:
    description: List alive players.
    usage: /listplayers
    permission: listplayers.use
    permission-message: You don't have permission to do that